The New York Times Clone
gurbuzertunga/nytimesclone pull request #1
Opened 2020-07-17 13:35 UTC by DcRonan

1. Created the webpage using Grid, Flex and float.

2. Added media queries 

3. Made responsive

2020-07-17 15:03 UTC, bertil291utn requested changes
**Status:** Changes requested 🟠  :shipit:? Not yet.

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish as the actual page, you required to do these changes, listed below: 

- [x] First of all, remove `.vscode` directory from your root project adding to `.gitignore` file


**Navigation Bar**

- [x] It has a "Hamburger button", a search icon and a link with text and should be on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
- [x] 'Log in' elements should be on the rightmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
- [x] Log in and subscribe buttons should be  squares and `color: #567B95;` color

![image](https://user-images.githubusercontent.com/24902525/87797993-0e694280-c811-11ea-9cb6-ac90b4c26113.png)

- [x] The NY Times logo should be a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

![image](https://user-images.githubusercontent.com/24902525/87797883-ed085680-c810-11ea-85a4-4da6efee6174.png)

- [x] Should be the entire page

![image](https://user-images.githubusercontent.com/24902525/87798283-6c962580-c811-11ea-95e8-14a472318925.png)

**Bottom part**

- [x] It should contain links to other articles with image previews on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

- [x] It should contain links to more popular articles on the rightmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

![image](https://user-images.githubusercontent.com/24902525/87798352-85064000-c811-11ea-8ede-33999e879f70.png)

**Footer**

- [ ] It should have a fixed position (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)). You're missing the footer fixed.

Original web page

![image](https://user-images.githubusercontent.com/24902525/87798639-e0d0c900-c811-11ea-9ec3-42ea38661ebc.png)

- [x] **The theory of inflation** section should have 4 rows. Check the original [page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)

![image](https://user-images.githubusercontent.com/24902525/87799366-b9c6c700-c812-11ea-9cf3-82b81aae8661.png)

- [x] Footer section should be a full page

![image](https://user-images.githubusercontent.com/24902525/87800064-90f30180-c813-11ea-9052-562923b64fce.png)

 

### Summary

- Some section are not accomplished full horizontal page, please check

- Be careful with the details colors, fonts, and sizes

<hr>


Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-07-17 15:03 UTC, bertil291utn commented on index.html
> +            </div>
It should contain links to other articles with image previews on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
- [x] Use `<a>` tag to wrap this div element

2020-07-17 15:03 UTC, bertil291utn commented on style.css
> +}
## No inefficient selectors[1]

- Try writing directly
```
.left-b-section {
  float: left;
}
```

###### _[1] [Good and bad  CSS practices](https://speckyboy.com/good-bad-css-practices/)_

2020-07-17 15:03 UTC, bertil291utn commented on style.css
> +}
## No inefficient selectors[1]

- Try writing directly
```
.right-b-section {
  float: right;
}
```

###### _[1] [Good and bad  CSS practices](https://speckyboy.com/good-bad-css-practices/)_

2020-07-17 15:03 UTC, bertil291utn commented on style.css
> +  flex-wrap: wrap;
## Using the Same Rule Repetitively[1]
- [ ] Create a class once and the use in each HTML tag where you need it.
- [ ] Delete all your `display:flex;` properties in entire CSS file
- [ ] Add your HTML tags

**CSS file**

```
.flex{
  display:flex;
}
```
**Html file**

```
<div class="flex">
```

<hr>

_[1] [Good and bad  CSS practices](https://speckyboy.com/good-bad-css-practices/)_

2020-07-20 10:46 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @DcRonan @gurbuzertunga** 
Good job with your new submission for this project :muscle:  
Your page passes most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:
- [x] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition, or you can create a new class.
- [ ]  Check out where is aligned the editor's pick section and then change your page to match the original:

| Yours | Original |
|:---:|:---:|
|![image](https://i.imgur.com/sa5Utctl.png) | ![image](https://i.imgur.com/1XmMimNl.png) |

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-07-20 10:46 UTC, andresporras3423 commented on style.css
> +}
Group selectors with the same style definition, or create a new class

2020-07-20 12:01 UTC, kitpao requested changes
# Hello @gurbuzertunga 

You have done nicely, however there is a difference in the positioning of your items in some places, please read ahead, don't forget the inline observations as well.

- [x] **[Mandatory]** Please fix your 'Editor's pick section' positioning **>If you believe this is a problem of different screensizes and you see yours correctly, please submit for another code review and send a screetshot in your comments<** : 

* This is the **original** page, see the alignment in respect to the inflation image, notice that horizontally the image should be a bit to the left, and vertically you can notice that the editor's pick section comes before the image:
![image](https://user-images.githubusercontent.com/53256139/87934334-75c30480-ca54-11ea-89b6-cba71cd629ce.png)
![image](https://user-images.githubusercontent.com/53256139/87934504-cc304300-ca54-11ea-93b5-57d556511463.png)

* In **your page**, the inflation image apprears first and it's not even touching the line, it is smaller as well (if you believe this is a problem from the difference in screensizes, please send the screenshot):
![image](https://user-images.githubusercontent.com/53256139/87935066-fd5d4300-ca55-11ea-8c8c-fa1340f084ed.png)
![image](https://user-images.githubusercontent.com/53256139/87935092-05b57e00-ca56-11ea-8abb-216eeda81e2b.png)

### ♻️ Status: Your project requires some additional changes ♻️

___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-07-20 12:01 UTC, kitpao commented on style.css
> +}
- [ ] **[MANDATORY]** For good coding practices, as the previous TSE indicated, follow DRY rule. 
  Just as a hint: you can use multiple classes for any element, so for example,

  If you use this line in many classes:
  `color: #fff;` and you use it for .class1, .class2, and .class3 
  you can put it inside a single class called for example "common-class" so it will look like this:
  **CSS**
  ```
  .class1 {
    font-size: 24px;
  }
  .class2 {
    font-size: 30px;
  }
  .class3 {
    font-size: 10px;
  }
  .common-class {
    color: #fff;
  }
  ```
  and in **HTML**:
  ```
  <nav class="class1 common-class">  <!-- this will have font size of 24px and color of #fff -->
  ...
  <div class="class2 common-class">  <!-- this will have font size of 30px and color of #fff -->
  ...
  <footer class="class3 common-class">   <!-- this will have font size of 10px and color of #fff -->
  ...
  ```
  * Go ahead and implement this change for repeated rules (for example your `width: 30%"` that repeats for 3 of your classes

2020-07-20 13:44 UTC, kitpao approved these changes
# Hi @DcRonan and @gurbuzertunga 

You fixed the required changes and thus, have completed your work 🌟

### Your project has been approved 👏
### You may merge to master and submit the project completition form 🚀


___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-07-20 13:50 UTC, merged